CabañasProyecto/Controllers/CabaniaController.cs
using CabañasProyecto.Models;
using Microsoft.AspNetCore.Mvc;

namespace CabañasProyecto.Controllers
{
    public class CabaniaController : Controller
    {
       
        [HttpGet]
        public IActionResult Index()
        {
            List<Cabania>? cabanias = null;
            using (CabaniasContext context = new CabaniasContext())
            {
                cabanias = context.Cabanias.ToList();
            }
            return View(cabanias);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cabania cabania)
        {
            using (CabaniasContext context = new())
            {
                context.Cabanias.Add(cabania);
                context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]

        public IActionResult Edit(int Id)
        {
            Cabania? cabania = null;
            using (CabaniasContext context = new())
            {
                cabania = context.Cabanias.Find(Id);
                if (cabania != null)
                {
                    return View(cabania);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
        }
        [HttpPost]
        public IActionResult Edit(int id, Cabania cab)
        {
            using (CabaniasContext context = new())
            {
                if(id != cab.Id)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    context.Cabanias.Update(cab);
                    context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
        }
        [HttpGet]
        public IActionResult Delete(Cabania cab)
        {
            using (CabaniasContext context = new())
            {
                if (cab != null)
                {
                    context.Cabanias.Remove(cab);
                    context.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

CabañasProyecto/Controllers/ClienteController.cs
using CabañasProyecto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace CabañasProyecto.Controllers
{
    public class ClienteController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            List<Cliente> clientes = null;
            using (CabaniasContext context = new CabaniasContext())
            {
                clientes = context.Clientes.ToList();   
            }
            return View(clientes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            using(CabaniasContext context = new CabaniasContext())
            {
                context.Clientes.Add(cliente);
                context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            using(CabaniasContext context = new())
            {
                Cliente? cliente = context.Clientes.Find(id);

                if (cliente != null)
                {
                    return View(cliente);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
          
        }
        [HttpPost]
        public IActionResult Edit(int id, Cliente cliente)
        {
          using(CabaniasContext context = new())
            {
                if (id != cliente.Id)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    context.Clientes.Update(cliente);
                    context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
        }
        [HttpGet]
        public IActionResult Delete(Cliente cliente)
        {
            using (CabaniasContext context = new())
            {
                if (cliente != null)
                {
                    context.Clientes.Remove(cliente);
                    context.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

CabañasProyecto/Controllers/ReservaController.cs
using CabañasProyecto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure.Internal;
using System.Collections.Generic;
using System.Numerics;

namespace CabañasProyecto.Controllers
{

    public class ReservaController : Controller
    {
        // Averiguar como poner un menu desplegable
        [HttpGet]
        public IActionResult Index()
        {
            List<Reserva> reservas = new();
            using (CabaniasContext c = new())
            {
                //Linq
                //List<Cabania> reservas2 = (from ca in c.Cabanias where ca.Estado == true select ca).ToList();
                //reservas = c.Cabanias.Where(pepe => pepe.Estado).ToList(); // sentencia lamba
                reservas = c.Reservas.ToList();
            }
            return View(reservas);
        }
        [HttpGet]
        public IActionResult Create()
        {
            List<Cabania> reservas = new();
            List<Cliente> clientes = new();
            using (CabaniasContext c = new())
            {
                reservas = c.Cabanias.Where(c => !c.Estado).ToList();
                clientes = c.Clientes.ToList();
                ViewBag.Cabanias = reservas;
                ViewBag.Clientes = clientes;
            }
            return View();
        }
       
        [HttpPost]
        public IActionResult Create(Reserva reserva)
        {
            Cabania? cabania = null;
            using (CabaniasContext c = new CabaniasContext())
            {
                //reserva.IdCabania = reserva.Id;
                //reserva.Id = 0;
                c.Reservas.Add(reserva);
                cabania = c.Cabanias.Find(reserva.IdCabania);
                if (cabania != null)
                {
                    cabania.Estado = true;
                    c.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(Reserva r)
        {
            Reserva? reserva = null;
            using (CabaniasContext context = new())
            {
                //reserva = (from ca in context.Reservas where ca.IdCabania == Id select ca).FirstOrDefault();
                int idR = r.Id;
                reserva = context.Reservas.Find(idR);
                if (reserva != null)
                {
                    return View(reserva);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            }
        [HttpPost]
        public IActionResult Edit(int id, Reserva reserva)
        {
            using (CabaniasContext context = new())
            {
                if (id != reserva.Id)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    context.Reservas.Update(reserva);
                    context.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
        }
        // Cuando eliminas la reserva hay q setear el estado en false de la cabaña
        [HttpGet]
        public IActionResult Delete(Reserva reserva)
        {
            Reserva? r = null;
            Cabania? cabania = null;
            using (CabaniasContext context = new())
            {
                if (reserva != null)
                {
                    int idR = reserva.Id;
                    r = context.Reservas.Find(idR);
                    cabania = context.Cabanias.Find(r.IdCabania);
                    context.Reservas.Remove(r);
                    if(cabania != null)
                    {
                        cabania.Estado = false;
                    }
                    context.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

 

CabañasProyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cabañas Alquileres</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CabañasProyecto.styles.css" asp-append-version="true" />
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="~/css/materialize.min.css" media="screen,projection" />
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper grey darken-3">
                <a href="#!" class="brand-logo center">Sistema de Alquileres</a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul class="right hide-on-med-and-down">
                    <li><a asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-controller="Cabania" asp-action="Index">Especialidad</a></li>
                    <li><a asp-controller="Cliente" asp-action="Index">Paciente</a></li>
                    <li><a asp-controller="Reserva" asp-action="Index">Medico</a></li>
                </ul>
            </div>
        </nav>

        <ul class="sidenav" id="mobile-demo">
            <li><a asp-controller="Home" asp-action="Index">Inicio</a></li>
            <li><a asp-controller="Cabania" asp-action="Index">Especialidad</a></li>
            <li><a asp-controller="Cliente" asp-action="Index">Paciente</a></li>
            <li><a asp-controller="Reserva" asp-action="Index">Medico</a></li>
        </ul>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Cabañas Alquileres
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="~/js/materialize.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(document).ready(function () {
            $('.sidenav').sidenav();
        })
    </script>
</body>
</html>